# Generated by Django 4.0.1 on 2022-06-08 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_post_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='imagen',
            field=models.ImageField(blank=True, default='/media/blog/2.jpg', null=True, upload_to='blog'),
        ),
    ]
